apiVersion: v1
kind: Service
metadata:
  name: hola-svc
spec:
  type: NodePort
  selector:
    app: hola-mundo
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080   # Puerto accesible desde el host